export const demoProjects = [
  {
    _id: 'demo-project-1',
    name: 'E-Commerce Platform',
    description: 'Product catalog, checkout, payment integration, and order operations for a modern commerce team.',
    color: '#6366f1',
    icon: 'EC',
    status: 'active',
    priority: 'high',
    tags: ['react', 'nodejs', 'mongodb'],
    progress: 35,
    members: [],
    taskStats: { total: 12, done: 3 },
  },
  {
    _id: 'demo-project-2',
    name: 'Mobile Banking App',
    description: 'Secure mobile banking workspace with biometric authentication and real-time account activity.',
    color: '#10b981',
    icon: 'MB',
    status: 'active',
    priority: 'critical',
    tags: ['mobile', 'fintech', 'security'],
    progress: 20,
    members: [],
    taskStats: { total: 5, done: 1 },
  },
  {
    _id: 'demo-project-3',
    name: 'AI Planning Assistant',
    description: 'Explainable assistant that highlights delivery risk and generates task breakdowns from goals.',
    color: '#f59e0b',
    icon: 'AI',
    status: 'active',
    priority: 'medium',
    tags: ['ai', 'analytics', 'automation'],
    progress: 25,
    members: [],
    taskStats: { total: 4, done: 1 },
  },
  {
    _id: 'demo-project-4',
    name: 'Design System v2',
    description: 'Component library refresh with dark mode, accessibility states, and reusable layout primitives.',
    color: '#ec4899',
    icon: 'UX',
    status: 'active',
    priority: 'medium',
    tags: ['design', 'a11y', 'storybook'],
    progress: 20,
    members: [],
    taskStats: { total: 5, done: 1 },
  },
];

export const demoTasks = [
  { _id: 'demo-task-1', title: 'Setup project architecture', status: 'done', priority: 'high', project: { _id: 'demo-project-1', name: 'E-Commerce Platform', color: '#6366f1' } },
  { _id: 'demo-task-2', title: 'Design database schema', status: 'done', priority: 'high', project: { _id: 'demo-project-1', name: 'E-Commerce Platform', color: '#6366f1' } },
  { _id: 'demo-task-3', title: 'Implement user authentication', status: 'done', priority: 'urgent', project: { _id: 'demo-project-1', name: 'E-Commerce Platform', color: '#6366f1' } },
  { _id: 'demo-task-4', title: 'Create product listing page', status: 'in-progress', priority: 'high', dueDate: new Date(Date.now() + 3 * 86400000).toISOString(), project: { _id: 'demo-project-1', name: 'E-Commerce Platform', color: '#6366f1' } },
  { _id: 'demo-task-5', title: 'Build shopping cart functionality', status: 'in-progress', priority: 'high', dueDate: new Date(Date.now() + 5 * 86400000).toISOString(), project: { _id: 'demo-project-1', name: 'E-Commerce Platform', color: '#6366f1' } },
  { _id: 'demo-task-6', title: 'Design checkout flow UI', status: 'review', priority: 'medium', project: { _id: 'demo-project-1', name: 'E-Commerce Platform', color: '#6366f1' } },
  { _id: 'demo-task-7', title: 'Integrate payment gateway', status: 'todo', priority: 'urgent', dueDate: new Date(Date.now() + 2 * 86400000).toISOString(), project: { _id: 'demo-project-1', name: 'E-Commerce Platform', color: '#6366f1' } },
  { _id: 'demo-task-8', title: 'Build order management dashboard', status: 'todo', priority: 'medium', project: { _id: 'demo-project-1', name: 'E-Commerce Platform', color: '#6366f1' } },
  { _id: 'demo-task-9', title: 'Implement search and filters', status: 'todo', priority: 'medium', project: { _id: 'demo-project-1', name: 'E-Commerce Platform', color: '#6366f1' } },
  { _id: 'demo-task-10', title: 'Setup CI/CD pipeline', status: 'backlog', priority: 'low', project: { _id: 'demo-project-1', name: 'E-Commerce Platform', color: '#6366f1' } },
  { _id: 'demo-task-11', title: 'Write API documentation', status: 'backlog', priority: 'low', project: { _id: 'demo-project-1', name: 'E-Commerce Platform', color: '#6366f1' } },
  { _id: 'demo-task-12', title: 'Implement biometric auth', status: 'in-progress', priority: 'urgent', project: { _id: 'demo-project-2', name: 'Mobile Banking App', color: '#10b981' } },
  { _id: 'demo-task-13', title: 'Build AI recommendation service', status: 'in-progress', priority: 'high', project: { _id: 'demo-project-3', name: 'AI Planning Assistant', color: '#f59e0b' } },
  { _id: 'demo-task-14', title: 'Design new color palette', status: 'in-progress', priority: 'high', project: { _id: 'demo-project-4', name: 'Design System v2', color: '#ec4899' } },
];

export const demoDashboard = {
  overview: {
    totalProjects: 4,
    totalTasks: 26,
    completedTasks: 8,
    inProgressTasks: 6,
    overdueTasks: 2,
    completionRate: 31,
  },
  tasksByStatus: { backlog: 5, todo: 6, 'in-progress': 6, review: 2, done: 7 },
  tasksByPriority: { low: 4, medium: 10, high: 8, urgent: 4 },
  weeklyData: Array.from({ length: 7 }, (_, index) => {
    const date = new Date(Date.now() - (6 - index) * 86400000);
    return { day: date.toLocaleDateString('en', { weekday: 'short' }), completed: [1, 3, 2, 4, 2, 3, 5][index] };
  }),
  recentTasks: [],
  activeProjects: demoProjects.slice(0, 3).map((project) => ({
    id: project._id,
    name: project.name,
    color: project.color,
    icon: project.icon,
    progress: project.progress,
  })),
};

export const demoInsights = {
  generatedAt: new Date().toISOString(),
  healthScore: 68,
  summary: {
    projects: 4,
    totalTasks: 26,
    openTasks: 18,
    completedTasks: 8,
    completionRate: 31,
    overdueTasks: 2,
    dueSoonTasks: 4,
    urgentOpenTasks: 3,
    unassignedTasks: 5,
  },
  riskTasks: [
    {
      id: 'demo-task-7',
      title: 'Integrate payment gateway',
      project: 'E-Commerce Platform',
      status: 'todo',
      priority: 'urgent',
      severity: 'high',
      reason: 'due within 48 hours, urgent priority',
    },
    {
      id: 'demo-task-12',
      title: 'Implement biometric auth',
      project: 'Mobile Banking App',
      status: 'in-progress',
      priority: 'urgent',
      severity: 'high',
      reason: 'urgent priority, security-sensitive work',
    },
  ],
  workload: [
    { name: 'Sarah Chen', active: 5, urgent: 1, overdue: 1, review: 0 },
    { name: 'David Kim', active: 4, urgent: 2, overdue: 0, review: 1 },
    { name: 'Unassigned', active: 3, urgent: 1, overdue: 0, review: 0 },
  ],
  recommendations: [
    {
      title: 'Handle "Integrate payment gateway" first',
      reason: 'due within 48 hours, urgent priority',
      impact: 'Reduces delivery risk immediately.',
      confidence: 0.92,
    },
    {
      title: 'Assign owners to urgent unassigned work',
      reason: 'Urgent work without ownership tends to stall.',
      impact: 'Improves accountability and follow-through.',
      confidence: 0.84,
    },
    {
      title: 'Clear the review queue',
      reason: 'Several tasks are waiting for review.',
      impact: 'Moves completed work across the finish line.',
      confidence: 0.78,
    },
  ],
};

export const generateDemoTaskBreakdown = (goal, projectName = 'the selected project') => [
  {
    title: 'Clarify scope and acceptance criteria',
    description: `Define success criteria for ${projectName}: ${goal}`,
    status: 'todo',
    priority: 'high',
    estimatedHours: 4,
    confidence: 0.86,
  },
  {
    title: 'Design the user workflow',
    description: `Map the core screens, states, and handoffs for ${projectName}.`,
    status: 'backlog',
    priority: 'high',
    estimatedHours: 4,
    confidence: 0.82,
  },
  {
    title: 'Implement backend contract',
    description: `Create the API/data model needed to support: ${goal}`,
    status: 'backlog',
    priority: 'medium',
    estimatedHours: 6,
    confidence: 0.78,
  },
  {
    title: 'Build frontend experience',
    description: `Ship the production UI and interaction states for ${projectName}.`,
    status: 'backlog',
    priority: 'medium',
    estimatedHours: 6,
    confidence: 0.74,
  },
  {
    title: 'Define rollout plan',
    description: `Plan release steps, owner handoff, and rollback notes for ${projectName}.`,
    status: 'backlog',
    priority: 'medium',
    estimatedHours: 3,
    confidence: 0.72,
  },
  {
    title: 'Create demo and documentation',
    description: `Prepare a concise walkthrough and implementation notes for: ${goal}`,
    status: 'backlog',
    priority: 'low',
    estimatedHours: 4,
    confidence: 0.7,
  },
  {
    title: 'Test and document the feature',
    description: `Verify edge cases and write concise implementation notes for ${projectName}.`,
    status: 'backlog',
    priority: 'low',
    estimatedHours: 3,
    confidence: 0.66,
  },
];
